name: Package Python to EXE and Release

on:
  push:
    branches:
      - main # 触发工作流的分支

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 拉取所有历史记录，以便获取标签信息

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies (if any)
        shell: pwsh
        run: |
          if (Test-Path requirements.txt) {
            pip install -r requirements.txt
          }

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Package with PyInstaller
        run: |
          pyinstaller --onefile --windowed --name your_program your_script.py # 确保这里是小写
        env:
          YOUR_MAIN_SCRIPT: your_script.py
          YOUR_PROGRAM_NAME: your_program

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: executable
          path: dist/your_program.exe # 确保这里是小写
